version: '3.8'

services:
  s${WEB_PORT}:
    build: .
    container_name: s${WEB_PORT}
    ports:
      - "${WEB_PORT}:80"
    environment:
      - DB_HOST=db${WEB_PORT}
      - DB_PORT=3306
      - DB_USER=gdps_user
      - DB_PASS=${DB_PASS}
      - DB_NAME=db${WEB_PORT}
    depends_on:
      - db${WEB_PORT}
    networks:
      - gdps_network

  db${WEB_PORT}:
    image: mariadb:10.6
    container_name: db${WEB_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_USER: gdps_user
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: db${WEB_PORT}
    volumes:
      - db_data_${WEB_PORT}:/var/lib/mysql
    ports:
      - "${DB_EXTERNAL_PORT}:3306"
    networks:
      - gdps_network

volumes:
  db_data_${WEB_PORT}:

networks:
  gdps_network:
    driver: bridge
