version: '3.8'
services:
  db:
    image: mariadb:10.6
    container_name: db8080
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./mysql_data:/var/lib/mysql

  gdps:
    image: cvolton/gmdprivateserver
    container_name: gdps_server
    restart: always
    ports:
      - "${GDPS_PORT}:80"
    depends_on:
      - db
    env_file: .env
    environment:
      MYSQL_HOST: "db"
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - ./gdps_data:/var/www/html/data
